--
-- PostgreSQL database dump
--

\restrict UM5hfJjSFk85liTCgvUcrIeyaC5gc5euNIgiWydDlzaMoWEFvhQhrl7asjmwN1B

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assuntos; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.assuntos (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    criado_em timestamp(6) with time zone NOT NULL,
    nome character varying(200) NOT NULL,
    disciplina_id bigint NOT NULL
);


ALTER TABLE public.assuntos OWNER TO mauricio;

--
-- Name: assuntos_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.assuntos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assuntos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bancas; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.bancas (
    id bigint NOT NULL,
    nome character varying(160) NOT NULL
);


ALTER TABLE public.bancas OWNER TO mauricio;

--
-- Name: bancas_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.bancas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bancas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalogo_instituicoes; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.catalogo_instituicoes (
    id bigint NOT NULL,
    nome character varying(200) NOT NULL
);


ALTER TABLE public.catalogo_instituicoes OWNER TO mauricio;

--
-- Name: catalogo_instituicoes_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.catalogo_instituicoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalogo_instituicoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comentarios; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.comentarios (
    id bigint NOT NULL,
    autor character varying(100) NOT NULL,
    criado_em timestamp(6) with time zone NOT NULL,
    curtidas integer NOT NULL,
    descurtidas integer NOT NULL,
    questao_id character varying(16) NOT NULL,
    texto text NOT NULL
);


ALTER TABLE public.comentarios OWNER TO mauricio;

--
-- Name: comentarios_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.comentarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comentarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO mauricio;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO mauricio;

--
-- Name: disciplinas; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.disciplinas (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    criado_em timestamp(6) with time zone NOT NULL,
    nome character varying(160) NOT NULL
);


ALTER TABLE public.disciplinas OWNER TO mauricio;

--
-- Name: disciplinas_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.disciplinas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disciplinas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: provas; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.provas (
    id bigint NOT NULL,
    ano integer NOT NULL,
    banca character varying(160) NOT NULL,
    cargo character varying(160) NOT NULL,
    criado_em timestamp(6) with time zone NOT NULL,
    instituicao_id bigint NOT NULL,
    modalidade character varying(40) NOT NULL,
    nivel character varying(80) NOT NULL
);


ALTER TABLE public.provas OWNER TO mauricio;

--
-- Name: provas_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.provas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.provas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questoes; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.questoes (
    id bigint NOT NULL,
    alternativas oid NOT NULL,
    ano integer NOT NULL,
    cargo character varying(160) NOT NULL,
    criado_em timestamp(6) with time zone NOT NULL,
    enunciado oid NOT NULL,
    gabarito character varying(8),
    id_question character varying(16) NOT NULL,
    modalidade character varying(40) NOT NULL,
    nivel character varying(80) NOT NULL,
    questao oid NOT NULL,
    texto_busca character varying(20000),
    disciplina_id bigint NOT NULL,
    assunto_id bigint NOT NULL,
    banca_id bigint NOT NULL,
    instituicao_id bigint NOT NULL,
    prova_id bigint
);


ALTER TABLE public.questoes OWNER TO mauricio;

--
-- Name: questoes_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.questoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subassuntos; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.subassuntos (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    criado_em timestamp(6) with time zone NOT NULL,
    nome character varying(200) NOT NULL,
    assunto_id bigint NOT NULL
);


ALTER TABLE public.subassuntos OWNER TO mauricio;

--
-- Name: subassuntos_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.subassuntos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subassuntos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: mauricio
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    criado_em timestamp(6) with time zone NOT NULL,
    email character varying(200) NOT NULL,
    nome character varying(160) NOT NULL,
    role character varying(20) NOT NULL,
    senha_hash character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT usuarios_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'VISITANTE'::character varying])::text[]))),
    CONSTRAINT usuarios_status_check CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'ATIVO'::character varying])::text[])))
);


ALTER TABLE public.usuarios OWNER TO mauricio;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: mauricio
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assuntos assuntos_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.assuntos
    ADD CONSTRAINT assuntos_pkey PRIMARY KEY (id);


--
-- Name: bancas bancas_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.bancas
    ADD CONSTRAINT bancas_pkey PRIMARY KEY (id);


--
-- Name: catalogo_instituicoes catalogo_instituicoes_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.catalogo_instituicoes
    ADD CONSTRAINT catalogo_instituicoes_pkey PRIMARY KEY (id);


--
-- Name: comentarios comentarios_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT comentarios_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: disciplinas disciplinas_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.disciplinas
    ADD CONSTRAINT disciplinas_pkey PRIMARY KEY (id);


--
-- Name: provas provas_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.provas
    ADD CONSTRAINT provas_pkey PRIMARY KEY (id);


--
-- Name: questoes questoes_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.questoes
    ADD CONSTRAINT questoes_pkey PRIMARY KEY (id);


--
-- Name: subassuntos subassuntos_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.subassuntos
    ADD CONSTRAINT subassuntos_pkey PRIMARY KEY (id);


--
-- Name: assuntos uk_assuntos_disciplina_nome; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.assuntos
    ADD CONSTRAINT uk_assuntos_disciplina_nome UNIQUE (disciplina_id, nome);


--
-- Name: bancas uk_bancas_nome; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.bancas
    ADD CONSTRAINT uk_bancas_nome UNIQUE (nome);


--
-- Name: catalogo_instituicoes uk_catalogo_instituicoes_nome; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.catalogo_instituicoes
    ADD CONSTRAINT uk_catalogo_instituicoes_nome UNIQUE (nome);


--
-- Name: disciplinas uk_disciplinas_nome; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.disciplinas
    ADD CONSTRAINT uk_disciplinas_nome UNIQUE (nome);


--
-- Name: provas uk_provas_cabecalho; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.provas
    ADD CONSTRAINT uk_provas_cabecalho UNIQUE (banca, instituicao_id, ano, cargo, nivel, modalidade);


--
-- Name: questoes uk_questoes_id_question; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.questoes
    ADD CONSTRAINT uk_questoes_id_question UNIQUE (id_question);


--
-- Name: subassuntos uk_subassuntos_assunto_nome; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.subassuntos
    ADD CONSTRAINT uk_subassuntos_assunto_nome UNIQUE (assunto_id, nome);


--
-- Name: usuarios uk_usuarios_email; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT uk_usuarios_email UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: idx_comentario_questao_id; Type: INDEX; Schema: public; Owner: mauricio
--

CREATE INDEX idx_comentario_questao_id ON public.comentarios USING btree (questao_id);


--
-- Name: idx_questao_ano; Type: INDEX; Schema: public; Owner: mauricio
--

CREATE INDEX idx_questao_ano ON public.questoes USING btree (ano);


--
-- Name: idx_questao_id_question; Type: INDEX; Schema: public; Owner: mauricio
--

CREATE INDEX idx_questao_id_question ON public.questoes USING btree (id_question);


--
-- Name: idx_questao_texto_busca; Type: INDEX; Schema: public; Owner: mauricio
--

CREATE INDEX idx_questao_texto_busca ON public.questoes USING btree (texto_busca);


--
-- Name: provas fk_provas_instituicao; Type: FK CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.provas
    ADD CONSTRAINT fk_provas_instituicao FOREIGN KEY (instituicao_id) REFERENCES public.catalogo_instituicoes(id);


--
-- Name: questoes fk_questoes_assunto; Type: FK CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.questoes
    ADD CONSTRAINT fk_questoes_assunto FOREIGN KEY (assunto_id) REFERENCES public.assuntos(id);


--
-- Name: questoes fk_questoes_banca; Type: FK CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.questoes
    ADD CONSTRAINT fk_questoes_banca FOREIGN KEY (banca_id) REFERENCES public.bancas(id);


--
-- Name: questoes fk_questoes_disciplina; Type: FK CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.questoes
    ADD CONSTRAINT fk_questoes_disciplina FOREIGN KEY (disciplina_id) REFERENCES public.disciplinas(id);


--
-- Name: questoes fk_questoes_instituicao; Type: FK CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.questoes
    ADD CONSTRAINT fk_questoes_instituicao FOREIGN KEY (instituicao_id) REFERENCES public.catalogo_instituicoes(id);


--
-- Name: subassuntos fkf6e6yyaks1wy63u536g52yn0m; Type: FK CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.subassuntos
    ADD CONSTRAINT fkf6e6yyaks1wy63u536g52yn0m FOREIGN KEY (assunto_id) REFERENCES public.assuntos(id);


--
-- Name: assuntos fkrywo4e4myklpl695fg2hmhha3; Type: FK CONSTRAINT; Schema: public; Owner: mauricio
--

ALTER TABLE ONLY public.assuntos
    ADD CONSTRAINT fkrywo4e4myklpl695fg2hmhha3 FOREIGN KEY (disciplina_id) REFERENCES public.disciplinas(id);


--
-- PostgreSQL database dump complete
--

\unrestrict UM5hfJjSFk85liTCgvUcrIeyaC5gc5euNIgiWydDlzaMoWEFvhQhrl7asjmwN1B

