# src/main/resources/application.properties

# =====================================
# APLICAÇÃO
# =====================================
spring.application.name=concurseiro-api
app.admin.api-key=M3a1u8r2i5c9i@o

# =====================================
# BANCO H2 PERSISTENTE EM ARQUIVO
# =====================================
spring.datasource.url=jdbc:h2:file:./data/concurseiro-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =====================================
# FLYWAY (MIGRAÇÕES)
# =====================================

# =====================================
# JPA / HIBERNATE
# =====================================
# Com Flyway, o Hibernate não deve tentar criar/alterar schema automaticamente.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =====================================
# CONSOLE H2 (APENAS DESENVOLVIMENTO)
# =====================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2